# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bananas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from tkinter import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(800, 600)
        MainWindow.setFixedWidth(650)
        MainWindow.setFixedHeight(300)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.channel_upX = QtWidgets.QPushButton(self.centralwidget)
        self.channel_upX.setGeometry(QtCore.QRect(90, 120, 100, 32))
        self.channel_upX.setObjectName("channel_up")
        self.channel_downX = QtWidgets.QPushButton(self.centralwidget)
        self.channel_downX.setGeometry(QtCore.QRect(90, 150, 110, 32))
        self.channel_downX.setObjectName("channel_down")
        self.oneX = QtWidgets.QPushButton(self.centralwidget)
        self.oneX.setGeometry(QtCore.QRect(230, 130, 31, 32))
        self.oneX.setObjectName("one")
        self.twoX = QtWidgets.QPushButton(self.centralwidget)
        self.twoX.setGeometry(QtCore.QRect(280, 130, 31, 32))
        self.twoX.setObjectName("two")
        self.threeX = QtWidgets.QPushButton(self.centralwidget)
        self.threeX.setGeometry(QtCore.QRect(330, 130, 31, 32))
        self.threeX.setObjectName("three")
        self.volume_upX = QtWidgets.QPushButton(self.centralwidget)
        self.volume_upX.setGeometry(QtCore.QRect(390, 120, 100, 32))
        self.volume_upX.setObjectName("volume_up")
        self.volume_downX = QtWidgets.QPushButton(self.centralwidget)
        self.volume_downX.setGeometry(QtCore.QRect(390, 150, 110, 32))
        self.volume_downX.setObjectName("volume_down")
        self.brightness_upX = QtWidgets.QPushButton(self.centralwidget)
        self.brightness_upX.setGeometry(QtCore.QRect(240, 180, 111, 32))
        self.brightness_upX.setObjectName("brightness_up")
        self.brightness_downX = QtWidgets.QPushButton(self.centralwidget)
        self.brightness_downX.setGeometry(QtCore.QRect(240, 210, 131, 32))
        self.brightness_downX.setObjectName("brightness_down")
        self.powerX = QtWidgets.QPushButton(MainWindow)
        self.powerX.setGeometry(QtCore.QRect(240, 80, 100, 32))
        self.powerX.setObjectName("powerX")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 10, 561, 61))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.channel_upX.setText(_translate("MainWindow", "Channel up"))
        self.channel_downX.setText(_translate("MainWindow", "Channel down"))
        self.oneX.setText(_translate("MainWindow", "1"))
        self.twoX.setText(_translate("MainWindow", "2"))
        self.threeX.setText(_translate("MainWindow", "3"))
        self.volume_upX.setText(_translate("MainWindow", "Volume up"))
        self.volume_downX.setText(_translate("MainWindow", "Volume down"))
        self.brightness_upX.setText(_translate("MainWindow", "Brightness up"))
        self.brightness_downX.setText(_translate("MainWindow", "Brightness down"))
        self.powerX.setText(_translate("MainWindow", "Power"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
